version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL_REMOUTE=postgresql://pavliushin.nikita:4cJQ3BOmeZtM@ep-red-breeze-a2qcelau.eu-central-1.aws.neon.tech/testGres?sslmode=require&schema=users&pgbouncer=true
      - DATABASE_URL=postgresql://root:root@postgres:5432/root?schema=kursach&pgbouncer=true&TrustServerCertificate=true
      - SECRET_FOR_JWT=Ahv)y,i]U9Q(QE_
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3001
      - HOST=localhost
    links:
      - redis
      - postgres
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
#    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
#      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redisdata:/var/lib/redis/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "root"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  redisdata:

